### ISSUE TITLE
Loki search reorders on refresh

### ISSUE THREAD

**Issue by negbie** [sipcapture/homer-ui#128]
Refreshing loki search multiple times seems to reorder results in time.

**Comment by adubovikov** [comment]
the data has been sent as it was received. Do you expect some sorting on backend ?

**Comment by negbie** [comment]
I would expect that the latest sent log line will stay on top no matter how often I refresh.

**Comment by negbie** [comment]
Grafana explore orders logs by time, latest on top.

**Comment by adubovikov** [comment]
this has been fixed. Can you please recheck and we will close the ticket

**Comment by negbie** [comment]
I will. Could you please rebuild the docker images to newest? Latest are still around 7.7.022

**Comment by negbie** [comment]
Tested with 7.7.028 and it's still not constant ordering by time.

**Comment by adubovikov** [comment]
for me it does correct ordering (ASC) It doesnt' dispaly same data (always next slice) but the ordering is correct

**Comment by negbie** [comment]
not for me. it starts with desc ordering but it gets screwed and every refresh shows next slice (not constant)

1582027418679
1582025532617
1582025481920
1582027414283

**Comment by mikegoodstadt** [comment]
Hi @negbie, The ordering should be correct now.
Let us know of any further issues - thanks!
